---
# create linode server and client instances
- name: create linode instances
  hosts: localhost
  vars_files:
      - group_vars/vars
      - group_vars/secret_vars

  pre_tasks:
    - name: check if linode api token is set
      fail:
        msg: "api_token is not set. Please set it in group_vars/secret_vars."
      when: api_token is not defined or api_token | d('', true) == ''

    - name: check if linode region is set
      fail:
        msg: "region is not set to a list of regions. Please set it in group_vars/vars."
      when: region is not defined or
            region | type_debug != 'list' or
            region | length < 1

    - name: check if linode instance type is set
      fail:
        msg: "type is not set. Please set it in group_vars/vars."
      when: type is not defined or type | d('', true) == ''

    - name: check if ssh_keys is set
      fail:
        msg: "ssh_keys or ssh_privatekey are not set. Please set them in group_vars/vars."
      when: ssh_keys is not defined or
            ssh_keys | type_debug != 'list' or
            ssh_keys | length < 1 or
            ssh_privatekey is not defined or ssh_privatekey | d('', true) == ''


  roles:
    - linode-env
    - linode-instance
    - linode-firewall
    - role: linode-dns
      when:
        - domain_name is defined
        - domain_name | d('', true) != ''
        - domain_service is not defined or domain_service | d('linode', true) == 'linode'

  tasks:
  # Update inventory

  - name: update group_vars
    blockinfile:
      path: ./group_vars/vars
      marker: "# {mark} INSTANCE VARS"
      block: |
        #jinja2: trim_blocks:False
        node_data:
          server:
            {%- for instance in host_info.results %}
            - name: {{ instance.instance.label }}
              instance:
                hostname: {{ instance.instance.label }}{% if domain_name != '' %}.{{ domain_name }}{% endif %}
                region: {{ instance.instance.region }}
                ip_pub1: {{ instance.networking.ipv4.public.0.address }}
                ip_priv1: {{ instance.networking.ipv4.vpc.0.address }}
                {%- if domain_name != '' %}
                aliases:
                  - {{ instance.instance.label }}.{{ domain_name }}
                {%- endif %}
            {%- endfor %}

  - name: create hosts file if it does not exist
    ansible.builtin.file:
      path: ./hosts
      state: touch
      modification_time: preserve
      access_time: preserve

  - name: add nodes to inventory
    blockinfile:
      path: ./hosts
      marker: "# {mark} LINODE INSTANCES"
      block: |
        #jinja2: trim_blocks:False
        {%- for r in [region]|flatten %}
        [{{ r }}]
        {%- for instance in host_info.results | selectattr('instance.region', 'eq', r) %}
        {{ instance.networking.ipv4.public.0.rdns }} region='{{ instance.instance.region }}'
        {%- endfor %}
        {% endfor %}
        [all:children]
        {%- for r in [region]|flatten %}
        {{ r }}
        {%- endfor %}

  - name: add hosts to in-memory inventory
    add_host:
      name: '{{ item.rdns }}'
      groups: '{{ item.region }}'
      ansible_host: '{{ item.ip }}'
      ansible_user: 'root'
      ansible_ssh_private_key_file: '{{ ssh_privatekey }}'
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_python_interpreter: '/usr/bin/python3'
    with_items: '{{ all_hosts }}'


# The rest of the playbook can execute in parallel on the instances
- hosts: '{{ hostvars.localhost.all_hosts | map(attribute="rdns") | list }}'
  gather_facts: false

  vars_files:
      - group_vars/vars
      - group_vars/secret_vars

  roles:
    - wait-for-ssh
    - setup-os
