# DNS
- name: check if hosts are in DNS
  # https://galaxy.ansible.com/ui/repo/published/linode/cloud/content/module/domain_info/
  linode.cloud.domain_info:
    api_token: '{{ api_token }}'
    domain: '{{ domain_name }}'
  register: domain_info

- name: remove old hosts, brokers, and controllers from dns
  # https://galaxy.ansible.com/ui/repo/published/linode/cloud/content/module/domain_record/
  linode.cloud.domain_record:
    api_token: '{{ api_token }}'
    domain_id: '{{ domain_info.domain.id }}'
    record_id: '{{ item[0].id }}'
    state: absent
  vars:
    instance_ips: "{{ dict(host_info.results | map(attribute='instance.label') | zip(host_info.results | map(attribute='networking.ipv4.public.0.address'))) }}"
  when:
    - domain_info|d([]) | length > 0
    - item[0].name is regex('-' + item[1] + '-')
    - (item[0].name in instance_ips and item[0].target != instance_ips[item[0].name])
  with_nested:
    - "{{ domain_info.records }}"
    - "{{ region }}"

- name: add new hosts to dns
  # https://galaxy.ansible.com/ui/repo/published/linode/cloud/content/module/domain_record/
  linode.cloud.domain_record:
    api_token: '{{ api_token }}'
    domain_id: '{{ domain_info.domain.id }}'
    name: '{{ item.instance.label }}'
    target: '{{ item.instance.ipv4[0] }}'
    ttl_sec: '{{ ttl_sec | default(omit) }}'
    type: 'A'
    state: present
  with_items: "{{ host_info.results }}"
  when:
    - domain_info|d([]) | length > 0
