- name: Apt update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Update grub on ubuntu 26.04
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_version'] is version('26.04', '>=')
  ansible.builtin.script:
    cmd: fix-grub.sh
    creates: /.grub_updated

- name: Apt upgrade packages
  ansible.builtin.apt:
    upgrade: safe

- name: Install basic packages
  ansible.builtin.apt:
    pkg:
      - chrony
      - curl
      - htop
      - rsync
      - python3
      - python3-passlib
      - acl
    state: latest
  register: package_updates
