- name: Zypper refresh repositories
  community.general.zypper:
    name: '*'
    state: latest
  changed_when: false

- name: Install basic packages
  community.general.zypper:
    pkg:
      - chrony
      - curl
      - htop
      - rsync
      - python3
      - python3-passlib
      - acl
    state: present
  register: setup_os_package_updates
